routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
// User
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/users', 'UserController@index')->name('users');
Route::get('/user/{username}/profile', 'UserController@user')->name('user');
Route::delete("/user/{username}/remove",  'UserController@remove')->name('remove_user');
Route::get("/user/{username}/messages", "UserController@messages")->name("messages");
Route::post("/user/{user_id}/block", "UserController@block_user")->name("block");
Route::post("/user/{user_id}/unblock", "UserController@unblock_user")->name("unblock");

// Company
Route::resource("companies", CompanyController::class);
Route::resource("ctags", CompanyTagController::class);

Route::get("/companies/{id}/images", "CompanyController@get_company_images")->name("companies.images");
Route::put("/companies/{id}/image", "CompanyController@add_new_image")->name("companies.image");
Route::delete("/companies/{id}/images/{image}", "CompanyController@delete_company_image")->name("companies.delete_image");

// Reports

Route::get("/reports", "ReportController@index")->name("reports");
//Packages
Route::get("/packageitems", "PackageItemsController@index")->name("packageitems");
Route::post("/packageitems", "PackageItemsController@store")->name("packageitems.store");
Route::put('/packageitem/{package}','PackageItemsController@update');

Route::get("/packages", "PackagesController@index")->name("packages");
Route::post("/packages", "PackagesController@store")->name("packages.store");

app/Activity.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Activity extends Model
{
    //
}

app/Admin.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class Admin extends Authenticatable
{
    //
    use Notifiable;

    protected $guarded = [''];

    protected $hidden = [
        'password', 'remember_token',
    ];

    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Alcohol.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Alcohol extends Model
{
    //
}

app/Astrological.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Astrological extends Model
{
    //
}

app/Company.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Company extends Model
{
    //

    protected $guarded = [''];
}

app/CompanyTag.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class CompanyTag extends Model
{
    //

    protected $table = "companytags";

    protected $guarded = [''];
}

app/Condition.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Condition extends Model
{
    //
}

app/Cuisine.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Cuisine extends Model
{
    //
}

app/Friend420.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Friend420 extends Model
{
    //
}

app/Haveanimal.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Haveanimal extends Model
{
    //
}

app/Identify.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Identify extends Model
{
    //
}

app/Industry.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Industry extends Model
{
    //
}

app/LookingFor.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class LookingFor extends Model
{
    //
    protected $table = "lookingfor";
}

app/Marital.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Marital extends Model
{
    //
}

app/MatchedList.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;


class MatchedList extends Model
{
    //
    protected $guarded = [];

    protected $table="matched_list";

    public function tossedUser(){

        return $this->hasOne("App\User", "id", "tossed_id");

    }
}

app/Param.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Param extends Model
{
    //

    protected $guarded = [];
}

app/Report.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Report extends Model
{
    //

    protected $guarded = ['id'];

    public function reporter(){
        return $this->hasOne("App\User", "id", "reporter_id");
    }

    public function user(){
        return $this->hasOne("App\User", "id", "user_id");
    }
}

app/Spiritual.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Spiritual extends Model
{
    //
}

app/Tabacco.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Tabacco extends Model
{
    //
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'firstname','lastname','username', 'email', 'password','phone','city','country','birthday','position','photo','video','filter','tossed','rewind'
    ];

    protected $guarded = [''];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function params() {
        return $this->hasMany("App\Param");
    }

    public function identifies() {
        return $this->hasOne("App\Identify", "id", "identify_id");
    }

    public function astrological() {
        return $this->hasOne("App\Astrological", "id", "astrological_id");
    }

    public function maritals(){
        return $this->hasOne("App\Marital", "id", "marital");
    }
    public function spiritual_belifes(){
        return $this->hasOne("App\Spiritual", "id", "spiritual");
    }
    public function alcohols() {
        return $this->hasOne("App\Alcohol", "id", "alcohol");
    }
    public function tobaccos(){
        return $this->hasOne("App\Tabacco", "id", "tabacco");
    }
    public function four20(){
        return $this->hasOne("App\Friend420", "id", "friendly420");
    }

    public function have_children(){
        return $this->hasOne("App\Havechildren", "id", "children");
    }
    public function have_animal(){
        return $this->hasOne("App\Haveanimal", "id", "animal");
    }
}

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta http-equiv="Content-Language" content="en">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Vegan Meet Dashboard</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no, shrink-to-fit=no" />
    <meta name="msapplication-tap-highlight" content="no">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <!-- Scripts -->
    <!-- <script src="{{ asset('js/app.js') }}" defer></script> -->
    <script src="{{ asset('js/main.js') }}" ></script>
    <script src="{{ asset('js/custom.js') }}" ></script>
    <!-- Fonts -->
    <!-- <link rel="dns-prefetch" href="//fonts.gstatic.com"> -->
    <!-- <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet"> -->

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link href="https://cdn.datatables.net/1.10.22/css/jquery.dataTables.min.css" rel="stylesheet">
</head>

<?php $currentRoute = Route::currentRouteName(); ?>

<body>
    <div class="app-container app-theme-white body-tabs-shadow fixed-sidebar fixed-header">
        <div class="app-header header-shadow">
            <div class="app-header__logo">
                <div class="logo-src"></div>
                <div class="header__pane ml-auto">
                    <div>
                        <button type="button" class="hamburger close-sidebar-btn hamburger--elastic"
                            data-class="closed-sidebar">
                            <span class="hamburger-box">
                                <span class="hamburger-inner"></span>
                            </span>
                        </button>
                    </div>
                </div>
            </div>
            <div class="app-header__mobile-menu">
                <div>
                    <button type="button" class="hamburger hamburger--elastic mobile-toggle-nav">
                        <span class="hamburger-box">
                            <span class="hamburger-inner"></span>
                        </span>
                    </button>
                </div>
            </div>
            <div class="app-header__menu">
                <span>
                    <button type="button"
                        class="btn-icon btn-icon-only btn btn-primary btn-sm mobile-toggle-header-nav">
                        <span class="btn-icon-wrapper">
                            <i class="fa fa-ellipsis-v fa-w-6"></i>
                        </span>
                    </button>
                </span>
            </div>
            <div class="app-header__content">
                <div class="app-header-left">

                </div>
                <div class="app-header-right">
                    <div class="header-btn-lg pr-0">
                        <div class="widget-content p-0">
                            <!-- Right Side Of Navbar -->
                            <ul class="navbar-nav ml-auto">
                                <!-- Authentication Links -->
                                @guest
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                                </li>
                                @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                                @endif
                                @else
                                <li class="nav-item dropdown">
                                    <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button"
                                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                        {{ Auth::user()->name }} <span class="caret"></span>
                                    </a>

                                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                        <a class="dropdown-item" href="{{ route('logout') }}" onclick="event.preventDefault();
                                                            document.getElementById('logout-form').submit();">
                                            {{ __('Logout') }}
                                        </a>

                                        <form id="logout-form" action="{{ route('logout') }}" method="POST"
                                            style="display: none;">
                                            @csrf
                                        </form>
                                    </div>
                                </li>
                                @endguest
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="app-main">
            <div class="app-sidebar sidebar-shadow">
                <div class="app-header__logo">
                    <!-- <div class="logo-src"> -->
                    <div class="logo">
                        <img src="/images/admin/logo-text.png" />
                    </div>
                    <div class="header__pane ml-auto">
                        <div>
                            <button type="button" class="hamburger close-sidebar-btn hamburger--elastic"
                                data-class="closed-sidebar">
                                <span class="hamburger-box">
                                    <span class="hamburger-inner"></span>
                                </span>
                            </button>
                        </div>
                    </div>
                </div>
                <div class="app-header__mobile-menu">
                    <div>
                        <button type="button" class="hamburger hamburger--elastic mobile-toggle-nav">
                            <span class="hamburger-box">
                                <span class="hamburger-inner"></span>
                            </span>
                        </button>
                    </div>
                </div>
                <div class="app-header__menu">
                    <span>
                        <button type="button"
                            class="btn-icon btn-icon-only btn btn-primary btn-sm mobile-toggle-header-nav">
                            <span class="btn-icon-wrapper">
                                <i class="fa fa-ellipsis-v fa-w-6"></i>
                            </span>
                        </button>
                    </span>
                </div>
                <div class="scrollbar-sidebar">
                    <div class="app-sidebar__inner">
                        <ul class="vertical-nav-menu">
                            <li class="app-sidebar__heading">Dashboards</li>
                            <li>
                                <a href="{{route('home')}}" class="menu-item {{ $currentRoute == 'home'? 'mm-active' : ''}}">
                                    <i class="metismenu-icon pe-7s-rocket"></i>
                                    Dashboard
                                </a>
                            </li>
                            <li>
                                <a href="{{route('users')}}" class="menu-item {{ $currentRoute == 'users'? 'mm-active' : ''}}">
                                    <i class="metismenu-icon pe-7s-users">
                                    </i>Users
                                </a>
                            </li>
                            <li>
                                <a href="{{ route('reports') }}" class="menu-item">
                                    <i class="metismenu-icon pe-7s-attention">
                                    </i>Reports
                                </a>
                            </li>
                            <li>
                                <a href="{{ route('packageitems') }}" class="menu-item">
                                    <i class="metismenu-icon pe-7s-attention">
                                    </i>Package Items
                                </a>
                            </li>
                            <li>
                                <a href="{{ route('packages') }}" class="menu-item">
                                    <i class="metismenu-icon pe-7s-attention">
                                    </i>Packages
                                </a>
                            </li>
                            <li class="app-sidebar__heading">Company/Affilates</li>
                            <!-- <li>
                                <a href="{{ route('ctags.index') }}" class="menu-item">
                                    <i class="metismenu-icon pe-7s-pin">
                                    </i>Tags
                                </a>
                            </li> -->
                            <li>
                                <a href="{{ route('companies.index') }}" class="menu-item">
                                    <i class="metismenu-icon pe-7s-note2">
                                    </i>Companies
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            @yield('content')
        </div>
    </div>

</body>

</html>